[colors]
transparent_background_colors = true
[colors.bright]
black = "#444a73"
blue = "#9ab8ff"
cyan = "#b2ebff"
green = "#c7fb6d"
magenta = "#caabff"
red = "#ff8d94"
white = "#c8d3f5"
yellow = "#ffd8ab"

[colors.normal]
black = "#1b1d2b"
blue = "#82aaff"
cyan = "#86e1fc"
green = "#c3e88d"
magenta = "#c099ff"
red = "#ff757f"
white = "#828bb8"
yellow = "#ffc777"

[colors.primary]
background = "#222436"
foreground = "#c8d3f5"

[font]
size = 14
[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[window]
blur = true
decorations = "None"
decorations_theme_variant = "Dark"
opacity = 0.95

[window.padding]
x = 4
y = 4
